import type { Metadata } from "next";
import "./globals.css";
import LeftBar from "@/components/layouts/LeftBar";
import RightBar from "@/components/layouts/RightBar";

export const metadata: Metadata = {
  title: "My Twitter",
  description: "Generated by Alireza",
};

const styles = {
  c_container: `flex flex-row justify-between max-w-screen-md lg:max-w-screen-lg xl:max-w-screen-xl xxl:max-w-screen-xxl mx-auto`,
  mainPart: `flex-1 lg:min-w-[600px] border-x-[1px] border-borderGray`,
  leftBar: `px-2 xsm:px-4 xxl:px-8`,
  rightBar: `hidden lg:flex ml-4 md:ml-8 flex-1`,
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className={styles.c_container}>
          <div className={styles.leftBar}>
            <LeftBar />
          </div>
          <div className={styles.mainPart}>
            {children}
            {modal}
          </div>
          <div className={styles.rightBar}>
            <RightBar />
          </div>
        </div>
      </body>
    </html>
  );
}
